name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Clean Package File
        run: npx clear-package-json package.json -o package.json
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            package.json
            dist/
            LICENSE
            readme.md
